### ISSUE TITLE
Library formatted KeyError prevents user formatting.

### ISSUE THREAD

**Issue by judfs** [tabatkins/kdlpy#5]
```
config = {} 
try:
    config["foo"]
except KeyError as e:
    print(f"{e} missing from config. Please fix.")
```
```
'foo' missing from config. Please fix.
```

vs
```
config = kdl.parse("")
try:
    config["foo"]
except KeyError as e:
    print(f"{e} missing from config. Please fix.")
```
```
"No node with name 'foo'." missing from config. Please fix.
```
The library's formatting is getting in the way of providing something useful for the user.

**Comment by tabatkins** [comment]
Yup, you're right, I should just throw rather than message.

**Comment by tabatkins** [comment]
All right, 1.1.1 released with this fix. Since I last touched this library I've also gone much harder on linting and learned more about how to structure my types better, so a decent amount of refactoring accompanied this otherwise-tiny change. ^_^

Please let me know if I've inadvertently broken anything; the official testsuite passes, as did some manual tests I ran, but there's a chunk of the library that's not adequately tested right now.
