### ISSUE TITLE
Idea for more consistent NodeKey

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#6]
Currently `None` can mean either No or Any
`(None, None):matches nodes with no tag, regardless of name`

(the full current table of values with a consistent tabular syntax:
```
Value     	            	 	: Meaning  	.
Tag       	 Name        	 	: Tag      	Name
          	 "nodename" 		: any      	specified
(None     	, None      	)	: no       	any
(None     	, "nodename"	)	: no       	specified
("tagname"	, None      	)	: specified	any
("tagname"	, "nodename"	)	: specified	specified

```

Maybe instead a `""` could signify `any`, while `None` mean only `no`, and then you could also have a side benefit of consistent type - always a tuple of two strings?
```
Value     	            	 	: Meaning  	.
Tag       	 Name        	 	: Tag      	Name
(""       	,"nodename" 	)	: any      	specified
(None     	, ""        	)	: no       	any
(None     	, "nodename"	)	: no       	specified
("tagname"	, ""        	)	: specified	any
("tagname"	, "nodename"	)	: specified	specified
```

**Comment by tabatkins** [comment]
The issue is that `""` is a valid node name; *all* strings are valid (for both names and tags). So I need a non-string value to indicate the other values. (Two values, for tags.)

I agree it's slightly suboptimal that `None` indicates different things for name vs tag, but I'm a bit boxed in on ergonomics. All nodes have a name, so I only need to indicate the "any name" state, and using None for it is the most obvious, intuitive thing. Tags are optional, so I need to indicate both "no tag" and "any tag", and there's not an obvious second value to use. I'd also prefer for the simplest thing you write to be "any tag", as usually the tag won't matter, and that means plain string should do it.

I could, in theory, allow `None` in the tuple to mean "any tag", so `"foo"` and `(None, "foo")` were synonyms, but again, I'd then have to come up with a third value to indicate "no tag", and I don't see an obvious one.

The current design, where not saying anything about the tag indicates "any tag" and giving `None` as the tag indicates "no tag" seems to be the best ergonomics, even tho `None` as the node name indicates something else.

**Comment by tabatkins** [comment]
Following up on this, because I ended up commenting on a different issue:

I have indeed made NodeKey both more feature-ful and consistent now. The "tag" and "node" portions of NodeKey can now both be `None`, `...` (matching anything), a string, a regex, or a predicate function; the only difference in their behavior is that `None` matches any node name, similar to `...`, since node names can't be None in the first place. You can still pass a place NameKey if that's all you want, or a tuple of (TagKey, NameKey).
