### ISSUE TITLE
Add NodeConverters for any nodes 

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#9]
What if I'd like to have some common converter for all/any node names, tagless (which `None, None` covers) or with tags?
For example, I'd like to treat all nodes of the following format:
  - `NodeName`
  - `"Node  Name"`
  - `nodename`
  - `node-name`
  - `(a)"node_name-name           Name"`
  - etc.

Identical, so I thought I'd have a catch-all filter that converts each node to lower case and remove all the word separators

In the suggested format that would be `("","")` filter

(understand it's possible to enumerate all the nodes later and replace their names, but the filter approach seemed better as you wouldn't need to build the recursion yourself)

**Comment by tabatkins** [comment]
Yup, it was inconsistent that I allowed a None name in the tagged NodeKey, but not in the tagless NodeKey. Fixed in <https://github.com/tabatkins/kdlpy/commit/1b6c9ee85e07daa9c42e496a6fe113a6ee69844b>

**Comment by tabatkins** [comment]
In other words, the "just match any node whatsoever" NodeKey is now just `None`; consistent with `("foo", None)` matching any node with the given tag and `(None, None)` matching any tagless node.

**Comment by tabatkins** [comment]
Actually, reopening because I'm thinking about `valueConverters` now; since you can only specialize on tag I just take a string, but this prevents you from filtering "no tag" and "any tag" values.

There *is* a third obvious value that Python uses in some places to mean "I don't care": `...`. It's used by `numpy` in a similar fashion, so there's some consistency here.

Okay, so proposal is that we allow `...` to indicate "any tag". We *also* allow it to indicate "any name"; node names would treat `...` and `None` identically, since there's no way to have a "no name" state.

So the options would be either `nameKey` or `(tagKey, nameKey)`. For `tagKey`, `...` indicates "any tag", `None` indicates "no tag", and a string indicates "that tag name". For `nameKey`, both `...` and `None` indicate "any name", while a string indicates "that node name".

**Comment by tabatkins** [comment]
Yeah, I went ahead and implemented that in be8e86a
